version: "3"

services:
  api:
    build: ./Query_API/
    image: query_api
    command:  uvicorn Online_API:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    networks:
      - test_network

  label:
    build: ./Label_Query/
    image: label_query
    command: "python3 ./Label_Query.py http://host.docker.internal:8000/predict/"
    ports:
      - 8001:8001
    networks:
      - test_network
    depends_on:
      - api

networks:
  test_network:
    driver: bridge