version: "3"

services:
  stacking_model:
    build: ./
    image: 1885011292/integrated_model
    command: "python3 ./integrated_stacking_model.py"
    ports:
      - 8004:8004
    networks:
      - test_network


networks:
  test_network:
    driver: bridge